    <nav>
        <p class="wordmark">
            <span>R</span>achel <span>V</span>i Design
        </p>

        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="projects.html">Projects</a></li>
            <li><a href="commissions.html">Commissions</a></li>
            <li><a href="contact.html">Contact</a></li>
            <li><a href="about.html">About</a></li>
        </ul>
    </nav>