    <nav class="siteNav">
        <div id="menuToggle">
        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="#73406a" viewBox="0 0 256 256"><path d="M208,32H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32ZM192,184H64a8,8,0,0,1,0-16H192a8,8,0,0,1,0,16Zm0-48H64a8,8,0,0,1,0-16H192a8,8,0,0,1,0,16Zm0-48H64a8,8,0,0,1,0-16H192a8,8,0,0,1,0,16Z" ></path></svg>
        </div>
        <p class="wordmark">
            <span>R</span>achel <span>V</span>i Design
        </p>

        <ul class="navLinks">
            <li><a href="index.php">Home</a></li>
            <li><a href="projects.html">Projects</a></li>
            <li><a href="commissions.html">Commissions</a></li>
            <li><a href="contact.php">Contact</a></li>
            <li><a href="about.html">About</a></li>
        </ul>
    </nav>